DEPRECATED_SNAPS = [
  :campaign_keyword_expenditures,
  :campaign_listing_expenditures,
  :keyword_campaign_expenditures,
  :shop_stats_searchads_snapshot_daily_v2,
  :listing_summaries,
  :images_listing,
  :forums_threads,
  :forums_threads_posts,
  :treasuries,
  :treasury_listings,
  # This is not actually deprecated as we snapshot it to produce the listings
  # "view", but people should not tap it directly (always use listings instead)
  :sharded_listings_with_shop,
].freeze

SNAP_WARNINGS = {
 :listings => "NOTE: The Listings table does not include reserved (private) listings. Join with reseved_listings / ReservedListings if you want _all_ listings",
 :reserved_listings => "WARNING: Be careful. The Reserved Listings table contains listings that should never be pubicly displayed.  DO NOT sink listings from this table to a dataset.",
 :sharded_listings => "WARNING: This table is not being updated anymore. Use Listings table; it now is souced from the shards.",
 :sharded_reserved_listings => "WARNING: This table is not being updated anymore. Use ReservedListings table; it now is souced from the shards."
}.freeze

SNAP_COLUMNS = {

:application_data => [
  "application_id:long",
  "name",
  "excerpt",
  "description",
  "url",
  "mashery_account",
  "mashery_key_v2",
  "approver_admin_id:long",
  "approver_user_id:long",
  "create_date",
  "update_date",
  "users_of_app",
  "charge",
  "app_behavior",
  "approval_description",
],

:application_index => [
  "application_id:long",
  "application_shard",
  "user_id:long",
  "approved",
  "categories",
  "state",
  "slug",
  "launch_date",
  "create_date",
  "update_date",
  "migration_lock",
  "old_shard",
  "popularity_score",
],

:api_keys_index => [
  "api_key_id:long",
  "keystring",
  "app_id:long",
  "service_name",
  "shared_secret",
  "active",
  "is_restricted",
  "limit_qps",
  "limit_qpd",
  "limit_qps_auth",
  "limit_qpd_auth",
  "referral_tag",
  "create_date",
  "update_date",
  "migration_lock",
  "old_shard",
],

:api_key_access_tokens => [
  "api_key_access_token_id:long",
  "api_key_id:long",
  "user_id:long",
  "oauth_token",
  "oauth_token_secret",
  "oauth_verifier",
  "scope",
  "active",
  "api_key_request_token_id:long",
  "revoke_date",
  "create_date",
  "update_date",
],

:carts_index => [
  "cart_id",
  "type_id",
  "type_owner_id",
  "shard",
  "shop_id",
  "state",
  "listings_count",
  "create_date",
  "update_date",
  "last_access_date",
],

:currency_exchange_rates => [
  "currency_rate_id",
  "buyer_rate",
  "market_rate",
  "seller_rate",
  "source_currency_id",
  "target_currency_id",
  "data_source",
  "create_date",
  "update_date",
],

:payment_templates => [
  "payment_template_id:long",
  "shop_id:long",
  "user_id:long",
  "allow_bt",
  "allow_check",
  "allow_mo",
  "allow_other",
  "allow_paypal",
  "allow_gbuy",
  "allow_cc",
  "allow_gc",
  "city",
  "state",
  "zip",
  "country_id",
  "create_date",
  "update_date",
],

:shop_settings => [
  "id:long",
  "shop_id:long",
  "name",
  "value:string",
  "create_date:timestamp",
  "update_date:timestamp"
],

:shop_stats_searchads_snapshot_daily_v2 => [
  "snapshot_key",
  "shop_id",
  "campaign_id",
  "keyword",
  "listing_id:long",
  "reference_timestamp",
  "view_count",
  "click_count",
  "spent_total",
  "create_date",
  "update_date",
],

:dbindex_categories => [
  "category_id:long",
  "name",
  "meta_title",
  "meta_keywords",
  "meta_description",
  "page_description",
  "page_title",
  "listing_enabled",
  "browsing_enabled",
  "path",
  "num_children",
  "created",
  "modified"
],

:images => [
  "image_id",
  "type_id",
  "owner_id",
  "full_height",
  "full_width",
  "hex_code",
  "version",
  "secret",
  "storage_volume",
  "file_extension",
  "create_date",
  "update_date"
],

:listings_tags => [
  "listings_tag_id",
  "listing_id:long",
  "shop_id",
  "tag",
  "sequence",
  "created",
  "modified",
  "language"
],

:listing_translations => [
  "listing_id:long",
  "shop_id:long",
  "language",
  "title",
  "description",
  "create_date:long",
  "update_date:long",
],

:shop_stats_searchads_attributions_daily => [
  "attributions_key",
  "shop_id",
  "campaign_id",
  "attribution_type_id",
  "reference_timestamp",
  "count",
  "revenue_total",
  "currency_code",
  "create_date",
  "update_date",
],

:listings => [
  "shop_id:long",
  "listing_id:long",
  "user_id:long",
  "state",
  "is_available:int",
  "is_displayable:int",
  "is_searchable:int",
  "admin_flags:long",
  "seller_flags:long",
  "title",
  "description",
  "price:long",
  "currency_code",
  "quantity:int",
  "section_id:long",
  "featured_rank:int",
  "image_key",
  "create_date:long",
  "ending_date:long",
  "original_create_date:long",
  "update_date:long",
  "state_date:long",
  "category_id:long",
  "path",
  "sharded_tags",
  "sharded_state:int",
  "tags"
],

# "WARNING: This table is not being updated anymore. Use Listings table; it now is souced from the shards."
:sharded_listings => [
  "shop_id:long",
  "listing_id:long",
  "user_id:long",
  "state:int",
  "is_available:int",
  "is_displayable:int",
  "is_searchable:int",
  "admin_flags:long",
  "seller_flags:long",
  "title",
  "description",
  "price:long",
  "currency_code",
  "quantity:int",
  "section_id:long",
  "featured_rank:int",
  "image_key",
  "create_date:long",
  "ending_date:long",
  "original_create_date:long",
  "update_date:long",
  "state_date:long",
  "category_id:long",
  "path",
  "sharded_tags"
],

# WARNING: Be careful. The Reserved Listings table contains listings that
# should never be pubicly displayed. Think twice before you sink listings
# from this table to a dataset."
:reserved_listings => [
  "shop_id:long",
  "listing_id:long",
  "user_id:long",
  "state",
  "is_available:int",
  "is_displayable:int",
  "is_searchable:int",
  "admin_flags:long",
  "seller_flags:long",
  "title",
  "description",
  "price:long",
  "currency_code",
  "quantity:int",
  "section_id:long",
  "featured_rank:int",
  "image_key",
  "create_date:long",
  "ending_date:long",
  "original_create_date:long",
  "update_date:long",
  "state_date:long",
  "category_id:long",
  "path",
  "sharded_tags",
  "sharded_state:int",
  "tags"
],

# "WARNING: This table is not being updated anymore. Use ReservedListings table; it now is souced from the shards."
:sharded_reserved_listings => [
  "shop_id:long",
  "listing_id:long",
  "user_id:long",
  "state:int",
  "is_available:int",
  "is_displayable:int",
  "is_searchable:int",
  "admin_flags:long",
  "seller_flags:long",
  "title",
  "description",
  "price:long",
  "currency_code",
  "quantity:int",
  "section_id:long",
  "featured_rank:int",
  "image_key",
  "create_date:long",
  "ending_date:long",
  "original_create_date:long",
  "update_date:long",
  "state_date:long",
  "category_id:long",
  "path",
  "sharded_tags"
],

:listing_processing => [
    'shop_id',
    'listing_id',
    'is_transaction_copy',
    'listing_processing_id:long',
    'min_processing_days',
    'max_processing_days',
    'min_expedited_processing_days',
    'max_expedited_processing_days',
    'is_expedited_processing_offered',
    'expedited_processing_cost',
    'currency_code',
    'create_date',
    'update_date'
],


:listing_images => [
  "listing_images_key",
  "listing_id:long",
  "shop_id",
  "image_id",
  "rank",
  "create_date",
  "update_date",
],

:listing_anchor_text => [
  "listing_id_url",
  "listing_id:long",
  "url",
  "title",
  "anchor_text",
  "author",
  "create_date",
  "update_date",
],

:sharded_listings_with_shop => [
  "shop_id:long",
  "listing_id:long",
  "user_id:long",
  "state:int",
  "is_available:int",
  "is_displayable:int",
  "is_searchable:int",
  "admin_flags:long",
  "seller_flags:long",
  "title",
  "description",
  "price:long",
  "currency_code",
  "quantity:int",
  "section_id:long",
  "featured_rank:int",
  "image_key",
  "create_date:long",
  "ending_date:long",
  "original_create_date:long",
  "update_date:long",
  "state_date:long",
],

:listing_summaries => [
  "listing_id:long",
  "state",
  "title",
  "creation_tsz:timestamp",
  "last_modified_tsz:timestamp",
  "price:float",
  "tags",
  "user_id:long",
  "image_listing_id:long",
  "quantity:int",
  "section_id:long",
  "shop_name",
  "ship_to",
],

:shop_data => [
  "shop_id:long",
  "status",
  "status_date",
  "user_id:long",
  "billing_user_id:long",
  "banner_id:long",
  "lat",
  "lon",
  "city",
  "region",
  "name",
  "headline",
  "message",
  "alchemy_message",
  "message_to_buyers",
  "active_listing_count",
  "is_frozen",
  "is_vacation",
  "is_nipsa",
  "shipping_score",
  "create_date:timestamp",
  "update_date:timestamp",
],

# create_date seems wrong for some reason, use from user_details instead
:users_index => [
  "user_id:long",
  "login_name",
  "primary_email",
  "avatar_id:long",
  "is_seller",
  "is_mute",
  "is_forum_mute",
  "is_frozen",
  "is_admin",
  "lat",
  "lon",
  "user_state",
  "last_login_date:int",
  "location_update_date:int",
  "create_date:int",
  "update_date:int",
  "can_receive_email",
  "first_name",
  "last_name",
  "is_name_withheld",
  "user_shard",
],

:user_details => [
  "user_id:long",
  "login_name",
  "first_name",
  "last_name",
  "bio",
  "tags",
  "materials",
  "how_they_heard",
  "country_id:long",
  "region",
  "city",
  "transaction_buy_count:int",
  "transaction_sold_count:int",
  "was_featured_seller",
  "state",
  "referred_by_user_id:long",
  "is_email_confirmed",
  "join_date:int",
  "name_modified_date:int",
  "create_date:int",
  "update_date:int",
  "referred_user_count:int",
  "location",
  "gender",
  "birth_month",
  "birth_day",
  "birth_year",
  "geonameid",
],

:user_api_keys => [
  "user_id:long",
  "api_key_id:long",
  "active:long",
  "create_date:long",
  "update_date:long",
],

:taxonomies => [
  "taxonomy_id:long",
  "top_level_id:long",
  "name",
  "metadata",
  "create_date",
  "update_date",
],

:taxonomy_listings_cache_1 => [
  "taxonomy_listing_id:long",
  "taxonomy_id:long",
  "listing_id:long",
  "listing_data",
  "price",
  "position:int",
  "create_date",
  "update_date",
  "destination_country_id:long",
  "destination_region_id:long",
],

:transactions => [
  "transaction_id:long",
  "seller_user_id:long",
  "buyer_user_id:long",
  "creation_tsz:timestamp",
  "paid_tsz:timestamp",
  "shipped_tsz:timestamp",
  "price",
  "currency_code",
  "quantity",
  "tags_str",
  "materials_str",
  "image_listing_id",
  "receipt_id",
  "shipping_cost",
  "listing_id:long",
  "seller_feedback_id:long",
  "buyer_feedback_id:long",
  "transaction_type",
  "usd_price:float",
  "usd_subtotal_price:float",
  "last_modified_tsz:timestamp"
],

:transactions_full => [
  "transaction_id:long",
  "title:string",
  "description:string",
  "seller_user_id:long",
  "buyer_user_id:long",
  "creation_tsz:timestamp",
  "paid_tsz:timestamp",
  "shipped_tsz:timestamp",
  "price:float",
  "currency_code:string",
  "quantity:long",
  "image_listing_id:long",
  "receipt_id:long",
  "shipping_cost:float",
  "listing_id:long",
  "seller_feedback_id:long",
  "buyer_feedback_id:long",
  "transaction_type:string",
  "images_listing_id:long",
  "suppressed:bool",
  "buyer_price:float",
  "buyer_currency_code:string",
  "buyer_shipping_cost:float",
  "buyer_tax_cost:float",
  "usd_price:float",
  "usd_shipping_cost:float",
  "usd_tax_cost:float",
  "tax_cost:float",
  "coupon_discount:float",
  "usd_coupon_discount:float",
  "buyer_coupon_discount:float",
  "shipping_discount:float",
  "usd_shipping_discount:float",
  "buyer_shipping_discount:float",
  "subtotal_price:float",
  "usd_subtotal_price:float",
  "buyer_subtotal_price:float",
  "coupon_id:long",
  "tags_str:string",
  "materials_str:string",
  "listing_type:long",
  "listing_inventory_id:long",
  "variation_data_version:long",
  "required_variation_details:string",
  "optional_variation_details:string",
  "returned:long"
],

:transactions_dead => [
  "transaction_dead_id:long",
  "transaction_id:long",
  "title",
  "description",
  "seller_user_id:long",
  "buyer_user_id:long",
  "creation_tsz:timestamp",
  "paid_tsz:timestamp",
  "shipped_tsz:timestamp",
  "price:float",
  "currency_code",
  "quantity:int",
  "tags_str",
  "materials_str",
  "image_listing_id:long",
  "receipt_id:long",
  "shipping_cost:float",
  "listing_id:long",
  "transaction_type",
  "tax_cost:float",
  "buyer_price:float",
  "buyer_shipping_cost:float",
  "buyer_currency_code",
  "buyer_tax_cost:float",
  "usd_price:float",
  "usd_shipping_cost:float",
  "usd_tax_cost:float",
  "last_modified_tsz:timestamp"
],

:transactions_shipping => [
    'transaction_id:long',
    'shop_id',
    'receipt_id',
    'buyer_user_id',
    'order_date',
    'shipped_date',
    'delivery_date',
    'delivery_date_source',
    'estimated_max_shipped_date',
    'orig_max_shipped_date',
    'estimated_shipped_date_changes',
    'estimated_max_delivery_date',
    'num_times_delayed',
    'delayed_max_shipped_date',
    'shipping_tracking_id',
    'is_expedited',
    'is_canceled',
    'create_date',
    'update_date:long',
    'shipping_profile_id',
    'listing_processing_id',
    'shipping_method_id',
    'listing_group_num',
    'paid_date',
    'shipping_label_id',
],


:favorite_users => [
  "favorite_user_key",
  "user_id:long",
  "target_user_id:long",
  "creation_tsz:timestamp",
  "is_public",
  "is_private",
],

:favorite_shops => [
  "favorite_shops_key",
  "user_id:long",
  "shop_id:long",
  "user_state",
  "shop_state",
  "shop_user_id:long",
  "create_date:timestamp",
],

:favorite_listings => [
  "favorite_listing_key",
  "user_id:long",
  "listing_id:long",
  "creation_tsz:timestamp",
  "is_public",
  "is_private",
],

:favoritelistings_users => [
  "favorite_listing_key",
  "user_id:long",
  "listing_id:long",
  "shop_id:long",
  "create_date:timestamp",
  "is_public",
  "is_private",
],

:images_listing => [
  "image_listing_id:long",
  "hex_code",
  "red",
  "green",
  "blue",
  "hue",
  "saturation",
  "brightness",
  "is_black_and_white",
  "creation_tsz",
  "marked_for_death",
  "listing_id:long",
  "rank:int",
],

:receipts => [
  # Why isn't receipt_id an int in the transactions table?
  "receipt_id",
  "order_id",
  "creation_tsz:timestamp",
  "total_price:float",
  "first_line",
  "second_line",
  "city",
  "state",
  "zip",
  "country_id:long",
],

:receipts_dead => [
  "receipts_dead_id:long",
  "receipts_dead_tsz:timestamp",
  "receipt_id:long",
  "order_id:long",
  "seller_user_id:long",
  "buyer_user_id:long",
  "creation_tsz:timestamp",
  "name",
  "first_line",
  "second_line",
  "city",
  "state",
  "zip",
  "country_id:int",
  "payment_method",
  "payment_email",
  "payment_secret",
  "message_from_seller",
  "message_from_buyer",
  "was_paid",
  "total_price:float",
  "total_shipping_cost:float",
  "currency_code",
  "message_from_payment",
  "was_shipped",
  "buyer_total_price:float",
  "buyer_total_shipping_cost:float",
  "buyer_currency_code",
  "total_tax_cost:float",
  "usd_total_price:float",
  "usd_total_shipping_cost:float",
  "usd_total_tax_cost:float",
  "coupon_id:long",
  "payment_transaction_id",
  "shop_name",
  "shop_id:long",
  "shipping_taxable",
  "applied_tax_rate:float"
],

:receipts_full => [
  "receipt_id:long",
  "order_id:long",
  "seller_user_id:long",
  "buyer_user_id:long",
  "creation_tsz:timestamp",
  "name",
  "first_line",
  "second_line",
  "city",
  "state",
  "zip",
  "country_id:int",
  "payment_method",
  "payment_email",
  "payment_secret",
  "message_from_seller",
  "message_from_buyer",
  "was_paid",
  "total_price:float",
  "total_shipping_cost:float",
  "currency_code",
  "message_from_payment",
  "was_shipped",
  "buyer_total_price:float",
  "buyer_currency_code",
  "buyer_total_shipping_cost:float",
  "total_tax_cost:float",
  "is_echeck",
  "checkout_version",
  "usd_total_price:float",
  "usd_total_shipping_cost:float",
  "usd_total_tax_cost:float",
  "buyer_total_tax_cost:float",
  "coupon_id:int",
  "coupon_discount:float",
  "usd_coupon_discount:float",
  "buyer_coupon_discount:float",
  "shipping_discount:float",
  "usd_shipping_discount:float",
  "buyer_shipping_discount:float",
  "subtotal_price:float",
  "usd_subtotal_price:float",
  "buyer_subtotal_price:float",
  "last_modified_tsz:int", # yup, this is an int and not a timestamp
  "payment_transaction_id",
  "shop_name",
  "shop_id:long",
  "shipping_taxable",
  "applied_tax_rate:float"
],

:forum_threads => [
  "forum_id:long",
  "forum_thread_id:long",
  "creator_user_id:long",
  "title",
  "post_count:int",
  "is_locked",
  "is_active",
  "update_date:timestamp",
  "create_date:timestamp",
],

:forum_thread_posts => [
  "forum_thread_id:long",
  "forum_thread_post_id:long",
  "user_id:long",
  "post",
  "post_order:int",
  "is_active",
  "is_admin",
  "is_noteworthy",
  "last_edit_time:timestamp",
  "update_date:timestamp",
  "create_date:timestamp",
],

# Deprecated
:forums_threads => [
  "forum_thread_id:long",
  "user_id:long",
  "user_id_latest:int",
  "title",
  "creation_tsz:timestamp",
  "last_updated_tsz:timestamp",
  "post_count:int",
  "forum_id:long",
  "active",
],

# Deprecated
:forums_threads_posts => [
  "forum_thread_post_id:long",
  "post",
  "user_id:long",
  "creation_tsz:timestamp",
  "post_order:int",
  "ip",
  "forum_thread_id:long",
  "active",
],

:treasuries => [
  "treasury_id",
  "creation_date:long",
  "last_updated_date:long",
  "title",
  "tags",
  "owner_id:long",
  "list_type",
  "mature",
  "locale",
],

:treasury_listings => [
  "treasury_listing_id",
  "treasury_id",
  "listing_id:long",
  "creation_date:long",
],

:treasury => [
  "treasury_id:long",
  "title",
  "description",
  "owner_id:long",
  "hotness:float",
  "mature:int",
  "private:int",
  "create_date:timestamp",
  "update_date:timestamp",
  "became_public_date:timestamp",
  "forum_id:long",
  "clicks:int",
  "views:int",
  "deleted:int"
],

:treasury_listing => [
  "treasury_listing_id",
  "treasury_id:long",
  "listing_id:long",
  "create_date:timestamp",
],

:feedback => [
  "feedback_id:long",
  "transaction_id:long",
  "creator_user_id:long",
  "target_user_id:long",
  "seller_user_id:long",
  "buyer_user_id:long",
  "creation_tsz:timestamp",
  "kiss_and_makeup_tsz:timestamp",
  "message",
  "value",
  "kiss_and_makeup_id:long",
],

:creator_feedback => [
  "transaction_id:long",
  "creator_user_id:long",
  "target_user_id:long",
  "shop_id:long",
  "feedback_id:long",
  "feedback_type:int",
  "message",
  "value",
  "image_feedback_id:long",
  "kiss_and_makeup_id:long",
  "create_date:long",
  "update_date:long"
],

:bill_charges => [
  "bill_charge_id:long",
  "creation_tsz:timestamp",
  "type",
  "type_id",
  "user_id:long",
  "amount:float",
  "currency_code",
  "creation_year",
  "creation_month",
  "last_modified_tsz:timestamp",
],

:bill_payments => [
  "bill_payment_id:long",
  "creation_tsz:timestamp",
  "type",
  "type_id",
  "user_id:long",
  "amount:float",
  "currency_code",
  "creation_year",
  "creation_month",
],

:billing_users => [
  "billing_user_id:long",
  "city",
  "state",
  "zip",
  "country_id:long",
  "user_id:long",
  "creation_tsz:timestamp",
],

:groups_users => [
  "groups_users_key",
  "group_id:long",
  "user_id:long",
  "application_essay",
  "user_role",
  "user_status",
  "create_date:timestamp",
  "update_date:timestamp",
  "login_name",
],

:groups_index => [
  'group_id:long',
  'group_shard',
  'name',
  'status',
  'create_date',
  'update_date',
  'migration_lock',
  'old_shard',
  'activity_score',
  'activity_score_last_updated',
  'group_type',
],

:groups_data => [
  'group_id:long',
  'long_description',
  'requirements',
  'related_links',
  'short_description',
  'type',
  'is_juried:int',
  'group_inauguration_date:int',
  'avatar_id:long',
  'banner_id:long',
  'location',
  'lat:int',
  'lon:int',
  'create_date:int',
  'update_date:int',
  'application_question',
  'application_essay_required:int',
  'google_map_zoom_level:int',
],

# use the circle_connections_from_connection_log to include only circles data
# for from_type_id and to_type_id, value type 2 corresponds to people
:connection_log => [
  "connection_key",
  "from_id:long",
  "from_type_id:long", #https://github.etsycorp.com/Engineering/Etsyweb/blob/master/phplib/ObjectType.php
  "to_id:long",
  "to_type_id:long", #https://github.etsycorp.com/Engineering/Etsyweb/blob/master/phplib/ObjectType.php
  "connection_type:int", #https://github.etsycorp.com/Engineering/Etsyweb/blob/master/phplib/Connection/Type.php
  "deleted:int",
  "creation_time:timestamp",
  "updated_time:timestamp",
],

#SearchAds tables

:keyword_campaign_expenditures => [
  "keyword_campaign_expenditures_id",
  "campaign_id:long",
  "mod_start_date:timestamp",
  "start_date:timestamp",
  "impression_count",
  "update_date:timestamp",
  "keyword",
],

:campaign_keyword_expenditures => [
  "campaign_keyword_expenditures_id",
  "campaign_id:long",
  "mod_start_date:timestamp",
  "start_date:timestamp",
  "impression_count",
  "update_date:timestamp",
  "keyword",
],

:searchads_keywords => [
  "keyword",
  "keyword_shard",
  "create_date:timestamp",
  "update_date:timestamp",
  "is_active",
  "migration_lock",
  "old_shard",
  "cpm",
],

:keyword_campaign_schedule => [
  "keyword_campaign_schedule_id",
  "campaign_id:long",
  "keyword",
  "impression_count",
  "impression_count_remaining",
  "cpm",
  "start_date:timestamp",
  "end_date:timestamp",
  "create_date:timestamp",
  "update_date:timestamp",
],

:campaign => [
  "campaign_id:long",
  "create_date:timestamp",
  "update_date:timestamp",
  "shop_id:long",
  "budget",
  "is_active",
  "auto_renew",
  "user_activated",
  "listings_scope_type",
],

:campaign_listing_expenditures => [
  "campaign_listing_expenditures_id",
  "campaign_id:long",
  "mod_start_date:timestamp",
  "start_date:timestamp",
  "impression_count",
  "update_date:timestamp",
  "listing_id:long",
],

:campaign_keywords => [
  "campaign_keywords_id:long",
  "campaign_id:long",
  "create_date:timestamp",
  "update_date:timestamp",
  "keyword",
  "is_active",
  "score",
  "excluded",
],

:campaign_index => [
  "campaign_id:long",
  "shop_id:long",
  "campaign_shard",
  "create_date:timestamp",
  "update_date:timestamp",
],

:campaign_keyword_sales => [
  "campaign_keyword_sales_id",
  "campaign_id:long",
  "keyword",
  "sale_date:timestamp",
  "sale_amount:float",
  "impression_count",
  "create_date:timestamp",
  "update_date:timestamp",
],

:campaign_instances => [
  "campaign_instance_id:long",
  "campaign_id:long",
  "start_date:timestamp",
  "end_date:timestamp",
  "hard_stop_date:timestamp",
  "budget:float",
  "sale_amount:float",
  "create_date:timestamp",
  "update_date:timestamp",
  "is_free:int",
],

:campaign_actions => [
  "campaign_action_id:long",
  "campaign_id:long",
  "user_id:long",
  "action",
  "budget:float",
  "action_date:timestamp",
  "applied",
  "create_date:timestamp",
  "update_date:timestamp",
],

:campaign_metrics => [
  "campaign_metrics_id",
  "campaign_id:long",
  "shop_id:long",
  "campaign_instance_id:long",
  "view_count:int",
  "click_count:int",
  "favorite_count:int",
  "purchase_count:int",
  "spent_total:float",
  "revenue:float",
  "create_date:timestamp",
  "update_date:timestamp"
],

:listings_properties_values => [
  "listings_property_id:long",
  "listing_id:long",
  "shop_id:long",
  "property_id:long",
  "value",
  "created:long",
  "modified:long"
],

:flag => [
  "id:long",
  "related_flag_id:long",
  "user_id:long",
  "reporter_user_id:long",
  "staff_id:long",
  "flag_type_id:long",
  "target_type:string",
  "target_id:long",
  "task_id:long",
  "subject:string",
  "reason:string",
  "status:string",
  "ref_count:int",
  "is_auto_action:int",
  "create_date:timestamp",
  "update_date:timestamp",
  "review_state:string"
],

:black_marks => [
  "pk:string",
  "shop_id:long",
  "mark_id:long",
  "deleted:int",
  "create_date:timestamp",
  "update_date:timestamp"
],

:merch_hub_curated_listing => [
    "curated_listing_id:string",
    "merch_hub_listing_set_id:long",
    "listing_id:long",
    "is_flagged:string",
    "state:string",
    "user_id:long",
    "create_date:timestamp",
    "update_date:timestamp"
],

:keyword_congestion => [
      'keyword_congestion_id',
      'keyword:string',
      'initial_forecast',
      'current_forecast',
      'scheduled',
      'served',
      'remain',
      'campaigns_using',
      'congestion',
      'version',
      'create_date:timestamp',
      'update_date:timestamp'
],

:campaign_keyword_schedule => [
      'campaign_keyword_schedule_id',
      'campaign_id',
      'keyword:string',
      'price',
      'scheduled',
      'served',
      'remain',
      'version',
      'create_date:timestamp',
      'update_date:timestamp'
],

:external_accounts => [
      'external_account_id',
      'owner_id',
      'owner_type_id',
      'external_account_type',
      'external_user_id',
      'external_username',
      'create_date',
      'update_date',
      'deleted',
      'flags',
      'share_flags'
],

:login_session_details => [
      'login_session_id',
      'user_id',
      'active',
      'agent',
      'ip',
      'country_code',
      'trace_cookie',
      'uaid',
      'accept_lang',
      'type',
      'source',
      'other_json',
      'create_date',
      'update_date',
],

:admin_logs => [
      'id',
      'create_date',
      'update_date',
      'target_type',
      'target_id',
      'reason_id',
      'notes'
],

:shop_sections => [
  'section_id',
  'shop_id',
  'name',
  'rank',
  'active_listing_count',
  'create_date',
  'update_date'
],

:facebook_account => [
  'facebook_account_id',
  'user_id',
  'create_date',
  'update_date'
],

:user_attributes => [
  'user_id_attribute',
  'user_id',
  'attribute',
  'value',
  'create_date',
  'update_date',
],

:user_preferences => [
  'user_id_preference_id',
  'user_id',
  'preference_id',
  'preference_setting',
  'create_date',
  'update_date'
],

:conversations => [
    'user_id',
    'conversation_id:long',
    'other_user_id',
    'other_login_name',
    'last_sender_id',
    'is_read',
    'is_visible',
    'is_sender',
    'is_trash',
    'is_sent',
    'is_inbox',
    'is_spam',
    'has_attachments',
    'message_count',
    'context_id',
    'context_type_id',
    'last_message_date',
    'last_message_other_date',
    'last_message_me_date',
    'update_date:long',
    'create_date',
],

:conversations_both_sides => [
    'user_id_conversation_id',
    'user_id',
    'conversation_id:long',
    'other_user_id',
    'other_login_name',
    'last_sender_id',
    'is_read',
    'is_visible',
    'is_sender',
    'is_trash',
    'is_sent',
    'is_inbox',
    'is_spam',
    'has_attachments',
    'message_count',
    'context_id',
    'context_type_id',
    'last_message_date',
    'last_message_other_date',
    'last_message_me_date',
    'update_date:long',
    'create_date',
],

:conversation_messages => [
    'origin_user_id',
    'conversation_id',
    'conversation_message_id',
    'sender_id',
    'message_order',
    'has_images',
    'update_date',
    'create_date',
    'nil',
],

:conversation_messages_with_messages => [
    'origin_user_id_conversation_message_id',
    'origin_user_id:long',
    'conversation_id:long',
    'conversation_message_id:long',
    'sender_id:long',
    'message',
    'message_order',
    'has_images',
    'update_date',
    'create_date',
],

:shop_shipping_label_data => [
  'address_id:long',
  'create_date:long',
  'download_preference',
  'is_onboarded',
  'is_suspended',
  'onboard_date:timestamp',
  'onboarding_payment_type',
  'origin_zipcode',
  'phone_number',
  'shop_id:long',
  'suspension_date:timestamp',
  'suspension_reason',
  'update_date:timestamp'
],

:shop_shipping_labels => [
  'shipping_label_id:long',
  'shop_id:long',
  'shipping_tracking_id',
  'receipt_id',
  'postage_cost',
  'signature_confirmation_fee',
  'delivery_confirmation_fee',
  'insured_mail_fee',
  'image_url',
  'image_filename',
  'image_expire_date',
  'mailing_date',
  'print_count',
  'first_print_date',
  'latest_print_date',
  'tracking_code',
  'mail_class',
  'state',
  'refund_state',
  'etsy_postage_cost',
  'provider_id',
  'create_date',
  'update_date',
  'provider_account_id',
  'refund_reason',
  'refund_submit_date',
  'spi_tracking_state_update_date',
  'spi_tracking_state',
  'spi_destination_country_id',
  'refund_state_date',
  'etsy_insured_mail_fee',
  'shipping_label_scanform_id',
  'package_type'
],

:attributee_attribution => [
  'attribution_id',
  'attributee_id:long',
  'action_type_id:int',
  'object_type_id:int',
  'object_id:long',
  'object_shardifier_id:long',
  'favoriter_id:long',
  'orig_attributee_id:long',
  'create_date',
  'update_date',
],

:email_depot => [
  'email_depot_id:long',
  'email',
  'user_id:long',
  'creation_time:long',
  'subject',
  'body',
  'headers',
  'inbound:int', # a tinyint flag
  'mailbox',
  'thread_id:long',
  'task_id:long',
  'owner_id:long',
  'state',
  'is_archived:int', # a tinyint flag
  'is_slatered:int', # a tinyint flag
],

:email_depot_kb_articles => [
  'email_depot_kb_articles_key', # compound primary key
  'email_depot_id:long',
  'status',
  'kb_article_id:long',
  'kb_article_group_id:long',
  'staff_id:long',
  'create_date:long',
],

:email_invitation => [
  'email_invitation_key',
  'user_id',
  'email_hash',
  'email_type',
  'import_batch_id',
  'creation_time',
],

:import_batches => [
  'import_batch_id',
  'user_id',
  'service',
  'creation_time',
],

:favorite_treasuries => [
  "favorite_treasury_key",
  "user_id:long",
  "treasury_id:long",
  "creation_tsz:timestamp",
  "is_public",
  "is_private",
],

:activity => [
  "activity_id:long",
  "owner_id:long",
  "owner_type_id:int",
  "subject_id:long",
  "subject_type_id:int",
  "verb_id:int",
  "object_id:long",
  "object_type_id:int",
  "creation_time:timestamp",
  "update_time:timestamp",
  "deleted:long",
  "public:int",
  "user_id:long",
  "circular_unique_id:long"
],

:collection => [
  "collection_id:long",
  "creator_id:long",
  "status:int",
  "privacy_level:int",
  "name",
  "slug",
  "create_date:timestamp",
  "update_date:timestamp"
],

:collection_listing => [
  "collection_listing_id",
  "collection_id:long",
  "listing_id:long",
  "collection_creator_id:long",
  "shop_id:long",
  "status:int",
  "create_date:timestamp",
  "update_date:timestamp"
],

:shop_transaction_review => [
  "transaction_id:long",
  "shop_id:long",
  "buyer_user_id:long",
  "receipt_id:long",
  "rating:int",
  "review",
  "is_anonymous:int",
  "is_deleted:int",
  "create_date:long",
  "update_date:long",
],

:shop_about => [
  "shop_id:long",
  "status",
  "story_headline",
  "story_leading_paragraph",
  "story",
  "pull_quote",
  "related_links",
  "create_date:long",
  "update_date:long",
],

:shop_about_members => [
  "shop_about_member_id:long",
  "shop_id:long",
  "name",
  "role",
  "bio",
  "rank:int",
  "status",
  "is_owner:int",
  "is_deleted:int",
  "create_date:long",
  "update_date:long",
],

:pages_index => [
  "page_id:long",
  "page_slug",
  "status:int",
  "type:int",
  "group_id:long",
  "page_name",
  "creator_id:long",
  "create_date:long",
  "update_date:long",
],

}.freeze

DATE_COL = {
  :api_key_access_tokens => "update_date",
  :api_keys_index => "update_date",
  :application_data => "update_date",
  :application_index => "update_date",
  :bill_charges => "last_modified_tsz",
  :bill_payments => "creation_tsz",
  :billing_users => "creation_tsz",
  :campaign => "update_date",
  :campaign_actions => "update_date",
  :campaign_index => "update_date",
  :campaign_instances => "update_date",
  :campaign_keywords => "update_date",
  :campaign_keyword_sales => "update_date",
  :campaign_keyword_expenditures => "update_date",
  :campaign_keyword_schedule => "update_date",
  :campaign_listing_expenditures => "update_date",
  :campaign_metrics => "update_date",
  :carts_index => "update_date",
  :connection_log => "updated_time",
  :conversations => "update_date",
  :conversations_both_sides => "update_date",
  :conversation_messages=> "update_date",
  :conversation_messages_with_messages => "update_date",
  :creator_feedback => "update_date",
  :currency_exchange_rates => "update_date",
  :dbindex_categories => "modified",
  :images => "update_date",
  :facebook_gift_friend_recommendation => "update_date",
  :facebook_account => "update_date",
  :favoritelistings_users => "create_date",
  :favorite_listings => "creation_tsz",
  :favorite_shops => "create_date",
  :favorite_users => "creation_tsz",
  :feedback => "creation_tsz",
  :forum_threads => "update_date",
  :forum_thread_posts => "update_date",
  :forums_threads => "last_updated_tsz",
  :forums_threads_posts => "creation_tsz",
  :groups_users => "update_date",
  :groups_index => "update_date",
  :groups_data => "update_date",
  :images_listing => "creation_tsz",
  :keyword_campaign_expenditures => "update_date",
  :keyword_campaign_schedule => "update_date",
  :keyword_congestion => "update_date",
  :listing_images => "update_date",
  :listing_processing=> "update_date",
  :listing_anchor_text => "update_date",
  :sharded_listings_with_shop => "update_date",
  :listing_summaries => "last_modified_tsz",
  :listings_tags=> "modified",
  :listing_translations => "update_date",
  :payment_templates=> "update_date",
  :receipts => "creation_tsz",
  :receipts_dead => "receipts_dead_tsz",
  :receipts_full => "last_modified_tsz",
  :searchads_keywords => "update_date",
  :shop_data => "update_date",
  :shop_settings => "update_date",
  :shop_stats_searchads_attributions_daily => "update_date",
  :shop_stats_searchads_snapshot_daily_v2 => "update_date",
  :taxonomies => "update_date",
  :taxonomy_listings_cache_1 => "update_date",
  :transactions => "last_modified_tsz",
  :transactions_full => "last_modified_tsz",
  :transactions_dead => "last_modified_tsz",
  :transactions_shipping => "update_date",
  :treasuries => "last_updated_date",
  :treasury_listings => "creation_date",
  :treasury => "update_date",
  :treasury_listing => "create_date",
  :user_api_keys => "update_date",
  :users_index => "update_date",
  :user_details => "update_date",
  :flag => "update_date",
  :black_marks => "update_date",
  :merch_hub_curated_listing => "update_date",
  :external_accounts => "update_date",
  :login_session_details => "update_date",
  :admin_logs => "update_date",
  :shop_sections => 'update_date',
  :shop_transaction_review => 'update_date',
  :shop_about => "update_date",
  :shop_about_members => "update_date",
  :user_attributes => 'update_date',
  :user_preferences => 'update_date',
  :shop_shipping_label_data => 'update_date',
  :shop_shipping_labels => 'update_date',
  :attributee_attribution => 'update_date',
  :email_depot => 'creation_time',
  :email_depot_kb_articles => 'create_date',
  :email_invitation => 'creation_time',
  :import_batches => 'creation_time',
  :favorite_listings => "creation_tsz",
  :activity => "update_time",
  :collection => "update_date",
  :collection_listing => "update_date",
  :pages_index => "update_date",
}.freeze

GROUP_COL = {
  :api_key_access_tokens => "api_key_access_token_id",
  :api_keys_index => "api_key_id",
  :application_index => "application_id",
  :application_data => "application_id",
  :bill_charges => "bill_charge_id",
  :bill_payments => "bill_payment_id",
  :billing_users => "billing_user_id",
  :campaign => "campaign_id",
  :campaign_actions => "campaign_action_id",
  :campaign_index => "campaign_id",
  :campaign_instances => "campaign_instance_id",
  :campaign_keyword_sales => "campaign_keyword_sales_id",
  :campaign_keywords => "campaign_keywords_id",
  :campaign_keyword_expenditures => "campaign_keyword_expenditures_id",
  :campaign_keyword_schedule => "campaign_keyword_schedule_id",
  :campaign_listing_expenditures => "campaign_listing_expenditures_id",
  :campaign_metrics => "campaign_metrics_id",
  :carts_index => 'cart_id',
  :connection_log => "connection_key",
  :conversations=> 'conversation_id',
  :conversations_both_sides=> 'user_id_conversation_id',
  :conversation_messages=> 'conversation_message_id',
  :conversation_messages_with_messages => 'origin_user_id_conversation_message_id',
  :creator_feedback => 'transaction_id',
  :currency_exchange_rates => 'currency_rate_id',
  :dbindex_categories => "category_id",
  :images => "image_id",
  :facebook_gift_friend_recommendation => "facebook_account_id",
  :facebook_account => "facebook_account_id",
  :favoritelistings_users => "favorite_listing_key",
  :favorite_listings => "favorite_listing_key",
  :favorite_shops => "favorite_shops_key",
  :favorite_users => "favorite_user_key",
  :feedback => "feedback_id",
  :forum_threads => "forum_thread_id",
  :forum_thread_posts => "forum_thread_post_id",
  :forums_threads => "forum_thread_id",
  :forums_threads_posts => "forum_thread_post_id",
  :groups_users => "groups_users_key",
  :groups_index => "group_id",
  :groups_data => "group_id",
  :images_listing => "image_listing_id",
  :keyword_campaign_expenditures => "keyword_campaign_expenditures_id",
  :keyword_campaign_schedule => "keyword_campaign_schedule_id",
  :keyword_congestion => "keyword_congestion_id",
  :listing_images => "listing_images_key",
  :listing_processing=> "listing_processing_id",
  :listing_anchor_text => "listing_id_url",
  :sharded_listings_with_shop => "listing_id",
  :listing_summaries => "listing_id",
  :listings_tags=> "listings_tag_id",
  :listing_translations => "listing_id",
  :payment_templates=> "payment_template_id",
  :receipts => "receipt_id",
  :receipts_dead => "receipts_dead_id",
  :receipts_full => "receipt_id",
  :searchads_keywords => "keyword",
  :shop_data => "shop_id",
  :shop_settings => "id",
  :shop_transaction_review => "transaction_id",
  :shop_about => "shop_id",
  :shop_about_members => "shop_about_member_id",
  :shop_stats_searchads_attributions_daily => "attributions_key",
  :shop_stats_searchads_snapshot_daily_v2 => "snapshot_key",
  :taxonomies => "taxonomy_id",
  :taxonomy_listings_cache_1 => "taxonomy_listing_id",
  :transactions => "transaction_id",
  :transactions_full => "transaction_id",
  :transactions_dead => "transaction_dead_id",
  :transactions_shipping => "transaction_id",
  :treasuries => "treasury_id",
  :treasury_listings => "treasury_listing_id",
  :treasury => "treasury_id",
  :treasury_listing => "treasury_listing_id",
  :user_api_keys => "user_id",
  :users_index => "user_id",
  :user_details => "user_id",
  :listings_properties_values => "listings_property_id",
  :flag => "id",
  :admin_logs => "id",
  :black_marks => "pk",
  :merch_hub_curated_listing => "curated_listing_id",
  :external_accounts => "external_account_id",
  :login_session_details => "login_session_id",
  :shop_sections => 'section_id',
  :user_attributes => "user_id_attribute",
  :user_preferences => "user_id_preference_id",
  :shop_shipping_label_data => "shop_id",
  :shop_shipping_labels => "shipping_label_id",
  :attributee_attribution => "attribution_id",
  :email_depot => 'email_depot_id',
  :email_depot_kb_articles => 'email_depot_kb_articles_key',
  :email_invitation => "email_invitation_key",
  :import_batches => "import_batch_id",
  :favorite_treasuries => "favorite_treasury_key",
  :activity => "activity_id",
  :collection => "collection_id",
  :collection_listing => "collection_listing_id",
  :pages_index => "page_id",
}.freeze

CLEANED_SNAP_COLUMNS = SNAP_COLUMNS.keys.inject({}) do |m, k|
  m[k] = SNAP_COLUMNS[k].map{|c| c.sub(/:\w+$/,"")}; m
end.freeze
